-- Add profile fields to users table
ALTER TABLE users 
ADD COLUMN profile_photo VARCHAR(500),
ADD COLUMN bio TEXT,
ADD COLUMN phone VARCHAR(20),
ADD COLUMN location VARCHAR(255),
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
